# Generated by Django 3.2.4 on 2021-07-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titls',
            new_name='title',
        ),
    ]
